### ISSUE TITLE
Add left spacing to the left of order lists.

### ISSUE THREAD

**Issue by johnnymatthews** [application-research/estuary-docs#1]
It looks like the padding/margin/spacing is off with ordered lists `<ol>`. The point `1`, `2`, and `3` below are all super far to the left.

![image](https://user-images.githubusercontent.com/9611008/123888677-091dde80-d922-11eb-981d-d3a3583a9158.png)

Unordered lists `<ul>` don't seem to have this problem:

![image](https://user-images.githubusercontent.com/9611008/123888811-48e4c600-d922-11eb-8e04-bbd9f3be15f6.png)

**Comment by jimmylee** [comment]
Resolved. thanks :-)
