### ISSUE TITLE
Getting `"error":"http: no such file"` when using the Curl upload example.

### ISSUE THREAD

**Issue by janzheng** [application-research/estuary-docs#7]
I'm trying to use both `curl` and Python's requests.post to upload a string as a file, but I keep getting a `"error":"http: no such file"` error.

Python:
```

def pin_JSON(jsondata):
  url = os.getenv('ESTUARY_URL')

  headers = CaseInsensitiveDict()
  headers["Authorization"] = "Bearer " + os.getenv('ESTUARY_API')
  headers["Accept"] = "application/json"
  print('api:', os.getenv('ESTUARY_API'), 'url:', url, 'data:', jsondata)
  files = {'file': ('file', 'some,data,to,send\nanother,row,to,send\n', 'text/plain')}

  resp = requests.post(url, verify=False,
    headers=headers, 
    files=files
    )

  print('estuary response:', resp)
  print('estuary response json:', resp.json())
  return resp.json()
```

and the curl (from the API docs)
```
curl -X POST https://shuttle-5.estuary.tech/content/add \
 -H "Authorization: Bearer TOKEN_HERE" \
 -H "Accept: application/json" \
 -H "Content-Type: multipart/form-data" \
 -F "text=test.json;type=text/plain"
```

What am I doing wrong here?

**Comment by jimmylee** [comment]
I just merged the fix, let me know if it works afterwards. Thanks for bearing with us @janzheng

**Comment by janzheng** [comment]
I think that's it! Thanks so much!

**Comment by johnnymatthews** [comment]
Hmm, I'm also not seeing this change as https://docs.estuary.tech/tutorial-uploading-your-first-file, even in a private browser: 

![image](https://user-images.githubusercontent.com/9611008/150851126-dad521b5-6c63-450a-b124-770c45d0a905.png)
